[package]
name = "aeon-engine"
version = "0.1.2022829"
edition = "2021"
authors = ["IntelliBitz", "Muthu Ramadoss", "AEON EAI Core"]
description = "aeon-engine: EAI: Exponential Intelligence for Any AI. - GAWD, GEMI & GMCP Multi-Agent Engine"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
candle-core = { version = "0.8.4" }
candle-nn = { version = "0.8.4" }
candle-transformers = { version = "0.8.4" }
tokenizers = "0.21.0"
hf-hub = "0.4.1"
anyhow = "1.0"
ureq = { version = "2.12", features = ["json", "tls"] }
rustyline = "15.0"
wasmer = { version = "3.1", features = ["cranelift", "sys"] }
wasmer-wasi = "3.1"
base64 = "0.22"
once_cell = "1.19"
libc = "0.2"
tiny_http = "0.12"
image = "0.25"
hound = "3.5"
shlex = "1.3"
signal-hook = "0.3"
md5 = "0.7"
log = "0.4"
env_logger = "0.11"
sha2 = "0.10"
tokio = { version = "1.37", features = ["full", "tracing"] }
console-subscriber = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "winerror"] }

[features]
default = []
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]
accelerate = ["candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
mkl = ["candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]

[profile.release]
opt-level = 3 # High performance
lto = true # Maximum optimization
codegen-units = 1 # Maximum parallelism in generated code
incremental = true # Speed up iterative builds
panic = "abort"
strip = true
